##basic

exp_name: "exp_demo"
exp_path: "/"
results_path: "results"
date_time: "2024-05-24_12-00-00"
env_hardware: 'A100'
gpu_id: 0
use_wandb: True
wandb_project: "project_demo"
seed: 42
mode: "train"
# data
data_name: "cifar10"
data_path: "dataset/"

# model
model_name: "resnet18"
checkpoint_path: "checkpoints"
hidden_size: 512

#training
train_batch_size: 128
epochs: 10
save_interval: 1
lr: 0.001
save_interval: 2
momentum: 0.5
log_interval: 100
